import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import classNames from "classnames";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <link
          rel="icon"
          type="image/svg+xml"
          href="memojis/7e539d2c025d7d4e48fbd6607da77b48-sticker.png"
        />
        {/* <meta name="generator" content={Astro.generator} />
		<title>{title}</title>
		<meta name="description" content={description} /> */}

        {/* social media */}
        {/* <meta property="og:title" content={title} />
		<meta property="og:type" content="website" />
		<meta property="og:description" content={description} /> */}
        <meta
          property="og:image"
          content="memojis/7e539d2c025d7d4e48fbd6607da77b48-sticker.png"
        />
        <meta property="og:url" content="https://ilcors-dev.github.io/me/" />
        <meta name="twitter:card" content="summary_large_image" />
      </head>
      <body
        className={classNames(
          "relative m-0 flex h-screen flex-col bg-white dark:bg-black dark:text-white",
          inter.className,
        )}
      >
        <div className="relative transition-all duration-300">
          {/* <ThemeSwitcher className="absolute right-4 z-10" /> */}
          <ThemeProvider attribute="class">{children}</ThemeProvider>
        </div>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
